### ISSUE TITLE
Alien Commander Bot Upgrades Multiple hives to the same type

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#61]
The bot will make 2, or sometimes 3, of the same hive type (crag, shift, shade)

**Comment by jonsextra** [comment]
What about just adding a delay b/w choosing hive types equal to how long it takes to upgrade a hive? So  it takes 20 sec to upgrade, just make it so that it doesn't choose a new hive type in less than 20 sec.

**Comment by Frozenclaw** [comment]
Hmm what if ya just made it so it prioritizes hive upgrade before hive drop?

**Comment by TheRealNin** [comment]
I'm not sure why or how everyone has all these ideas of how the fix the bug. The bug is with the way the tech tree handles hive upgrades, and then the bot is basically fallen victim to it.

 It's the same bug as when you click multiple hives and then start an upgrade. If you have enough res, it'll start upgrading them all.

**Comment by TheRealNin** [comment]
Well I have fixed this now but it's so horrible you might throw up. You've been warned.
Whenever an alien comm goes to *try* to upgrade a hive, it marks the type as done, so it won't ever try again. This prevents multiple hives of the same type. It also sometimes leaves an un-upgraded hive. Bleah.
